### ISSUE TITLE
Nextcloud logo doesn't appear

### ISSUE THREAD

**Issue by Jib-san** [Sebclem/hassio-nextcloud-backup#10]
Hi,

Really good idea to doing an hassio backup add-on to Nextcloud.

I've tried manual backup and it works perfectly, good job.

However, the Nextcloud logo doesn't appear on the header. Reviewed the code and i've seen that le logo picture is stocked on another ovh domain.

https://github.com/Sebclem/hassio-nextcloud-backup/blob/3005dc3ec79fae76ec695e7269b11199b9f4af34/nextcloud_backup/rootfs/opt/nextcloud_backup/views/index.ejs#L83

Can't you put it locally ? It would be better.

![logo_error](https://user-images.githubusercontent.com/13869992/75706551-aa107100-5cbd-11ea-8145-a235f46e8c08.jpg)

**Comment by Sebclem** [comment]
Hi,
Thank you for the report ! 
It's fixed with 0.7.4 . (That was a forgotten test)
