### ISSUE TITLE
Increasing timeout value

### ISSUE THREAD

**Issue by gody01** [Sebclem/hassio-nextcloud-backup#111]
**Describe the bug**
Getting timeout on backup creation:
Can't create new snapshot (Timeout awaiting 'request' for 5400000ms)

**To Reproduce**
It seems, that when influxdb is big enough timoeut happens.

**Expected behavior**
Wait a bit longer for HA to finish backup.
(At least configuration to increase timeout value.)

**System information**
-----------------------------------------------------------
 Add-on: Nextcloud Backup
 Easily backup your Home Assistant snapshots to Nextcloud
-----------------------------------------------------------
 Add-on version: 0.16.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.4  (aarch64 / odroid-n2)
 Home Assistant Core: 2022.2.6
 Home Assistant Supervisor: 2022.01.1
- If any, reverse proxy in fort on Nextcloud : 
nginx

**Additional context**
Session log:
[2022-02-12 11:49:50] [info]: 	Creating new snapshot...
[2022-02-12 13:19:50] [error]: 	Can't create new snapshot (Timeout awaiting 'request' for 5400000ms)
(node:347) UnhandledPromiseRejectionWarning: Can't create new snapshot (Timeout awaiting 'request' for 5400000ms)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:347) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:347) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

After a bit more time, backup has appeared and upload manualy started:
[2022-02-12 13:43:45] [info]: 	Downloading snapshot e6d77237...
[2022-02-12 13:44:28] [info]: 	Download success !
[2022-02-12 13:44:28] [info]: 	Uploading snap...

**Comment by Sebclem** [comment]
I have removed this hardcoded timeout value (I don't know why this take me this long to remove this). 
With the last version, you can now change the time out value in the addon configuration ( In Homme Assistant config not in the addon UI ) 👍
