### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by n76** [Sebclem/hassio-nextcloud-backup#14]
In the Settings->Backup screen one of the options for “Auto Backup” is “Dayly”. Should be spelled “Daily”.

Thanks for creating this Hass.io add on!

**Comment by n76** [comment]
Maybe I should close this as I see there is [a pull request](https://github.com/Sebclem/hassio-nextcloud-backup/pull/13/commits/c67846a66cb5bcfa3de9168f11b4c19e17be1e3d) with this fix already in it.

**Comment by Sebclem** [comment]
Yep, merged, i will make the release this afternoon.
