### ISSUE TITLE
Invalid nextcloud settings

### ISSUE THREAD

**Issue by SavageAUS** [Sebclem/hassio-nextcloud-backup#15]
Just installed the add on and I want to like it but I cannot get it to connect to my nextcloud. I have a domain and am using a reverse proxy so for my address on the add on I am using https://mynextcloud.mydomain.xyz and my username and password but I get the error message below.
```
[2020-05-12 20:29:45] [info]: Initilizing and checking webdav client...
[2020-05-12 20:29:45] [error]: Can't connect to Nextcloud (Error: getaddrinfo ENOTFOUND https https:443) !
[2020-05-12 20:29:47] [info]: Initilizing and checking webdav client...
[2020-05-12 20:29:47] [error]: Can't connect to Nextcloud (Error: getaddrinfo ENOTFOUND https https:443) ! 
```

**Comment by Sebclem** [comment]
Hi, it's normally work well with reverse proxy, i'm using one.

If you have https, enable SSL in setting, in `Hostname` simply add "mynextcloud.mydomain.xyz", no port (only if you use 443, if you use another port, add `:8080` for exemple), but most importent remove the `http` or `https` prefix in hostname.

**Comment by SavageAUS** [comment]
Simply removing http:// / https:// got it working. 
Thank you.

**Comment by FlashAndromeda** [comment]
> Simply removing http:// / https:// got it working. Thank you.

Helped me as well, might be useful to mention this on the config page.

**Comment by Hugo158415** [comment]
bravo,,,, ça fonctionne ;-)
