### ISSUE TITLE
SSL Switch has no effect in settings

### ISSUE THREAD

**Issue by cbellgit** [Sebclem/hassio-nextcloud-backup#16]
I have a local nextcloud instance that does not use SSL.  The settings page has a switch to turn off SSL and when I turn it off, I still get messages like "Can't connect to Nextcloud (Error: connect ECONNREFUSED 192.168.x.x:443) !"  When I cancel out and come back into settings, the SSL switch is turned back on, but the other settings like the hostname, etc. are still saved.

**Comment by Sebclem** [comment]
It's normally fixed with 0.7.6, i'm currently building images.

Let me know if it's work.

**Comment by cbellgit** [comment]
It works now.  Thank you!
