### ISSUE TITLE
Use this in docker installation

### ISSUE THREAD

**Issue by jds11111** [Sebclem/hassio-nextcloud-backup#183]
**Is your feature request related to a problem? Please describe.**
Before I switch to pure docker installation from HassOS, I need to get this addon working as a docker container.
I suspect that this is possible, and have made progress despite my ignorance on the subject.  I suppose I could use the Duplicati docker container, but yours is very nicely integrated with home assistant now.

**Describe the solution you'd like**
Probably just need a few lines in the docs to explain how to do this, or a
way to remove the code from requiring the supervisor?

**Describe alternatives you've considered**
So far, I have done the following:

`git clone https://github.com/Sebclem/hassio-nextcloud-backup `
`cd hassio-nextcloud-backup`
`docker build nextcloud_backup`

Everything seems to work just fine so far. Then I run the image:
`docker run 94ffff31605e`

But this throws some understandable errors:
```
curl: (6) Could not resolve host: supervisor
[21:53:48] ERROR: Something went wrong contacting the API
```
and 
`[2022-09-06 21:53:52] [error]:  Nextcloud config not found !`

The first error is understandable, because supervisor is not running on such an install.
The second, because I haven't written the config file yet, and not sure where to put it. I had
assumed that the file `config.json` is where I could make some small changes, like the UI port, 
but my changes there don't seem to show up in the docker image. In fact the docker image
has no port forwarding. 

**System information**
- Home Assistant Version :  Home Assistant 2022.8.7 Frontend 20220802.0 - latest 
- Home Assistant Supervisor Version : none
- Nextcloud Version : 24.0.3
- Addon version : latest
- If any, reverse proxy in fort on Nextcloud : none

**Additional context**
I am happy to help debug this change.  My installation is just test, not production so far.

**Comment by Sebclem** [comment]
Hi,

The main issue here is that you are not running a supervisor. 
Backups/snapshots are mades by the supervisor, this add-on only send a request to create a new one, download and upload it to your Nextcloud instance.

This add-on can't work without supervision, sorry.

**Comment by jds11111** [comment]
OK. Thanks for letting me know.

**Comment by petrkr** [comment]
Since some version  from 2022 there is possible run backup job even without supervisor. For example by trigger by Webhook (or schedule).

Would be nice to have automated backup to nextcloud also by using that. I have more kubernetes/container on server at home, do no have separated dedicated hardware for HA.
