### ISSUE TITLE
Fail to upload snapshot to nextcloud (HTTPError: Response code 413 (Request Entity Too Large)) !

### ISSUE THREAD

**Issue by GD-Dal** [Sebclem/hassio-nextcloud-backup#187]
Topic says it all I guess.
I get this error both while uploading existing snapshots and when creating new ones.
Snapshots are created, and the backup directory in NC as well, but when it comes to actually uploading the backup, it says:
Fail to upload snapshot to nextcloud (HTTPError: Response code 413 (Request Entity Too Large)) !

The settings has been set up to use the app password, as the doc describes.

One thing that could be worth mentioning, though: I use SWAG nginx proxy in front of the Nextcloud server.

**Comment by Sebclem** [comment]
Please check this pined issue: https://github.com/Sebclem/hassio-nextcloud-backup/issues/9
This can be caused by your nginx config

**Comment by GD-Dal** [comment]
> Please check this pined issue: #9 This can be caused by your nginx config

Following the instructions on that link seems to have solved the problem for me.
Thanks.
