### ISSUE TITLE
Service to trigger backup

### ISSUE THREAD

**Issue by aguiller31** [Sebclem/hassio-nextcloud-backup#236]
Hey,
I know this project is not maintained anymore but wouldn't it be nice to have a service in order to start a backup with a service ? This would allow to start it with an automation !

**Comment by Sebclem** [comment]
This project in not abandoned, l’m working on a big rewrite, you can follow the progress in #192 and on the `vue` branch

**Comment by aguiller31** [comment]
Sorry I haven't seen that ! You did an amazing job ! Thankhs

**Comment by Sebclem** [comment]
You can keep this request open as it's not listed in the rebuild tickets 👍
