### ISSUE TITLE
Keep X backup on local machine

### ISSUE THREAD

**Issue by pricard32** [Sebclem/hassio-nextcloud-backup#24]
Would like to see the ability to auto delete old backup on the HA machine.
When doing a lot of auto backup, it take a lot of space.

**Comment by Sebclem** [comment]
Already available:
In Nextcloud backup -> Click on the settings gear (top right) -> backup. And enable `Auto Clean Local Snapshots`
And like i say in readme `Auto Clean is executed after every upload and every day at 00h30`

**Comment by pricard32** [comment]
Wow, how can I delete my request ^^ !!!!!

**Comment by Sebclem** [comment]
Ahah no problem :wink:

**Comment by pricard32** [comment]
@Sebclem merci pour ton bon travail, je cherchais ce feature depuis longtemps!

**Comment by Sebclem** [comment]
Merci à toi pour ton retour ! N'hésite pas à ouvrir un ticket si tu trouve un bug ou autre !
