### ISSUE TITLE
Can't create new snapshot (UnhandledPromiseRejectionWarning)

### ISSUE THREAD

**Issue by Lenny5156** [Sebclem/hassio-nextcloud-backup#26]
I get this Error, when I start the backup process manually:
[2020-09-20 00:00:00] [debug]: Cron triggered !
[2020-09-20 00:00:00] [info]: Creating new snapshot...
[2020-09-20 00:40:01] [error]: Can't create new snapshot (Timeout awaiting 'request' for 2400000ms)
(node:248) UnhandledPromiseRejectionWarning: ReferenceError: status is not defined
    at /opt/nextcloud_backup/tools/webdavTools.js:296:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-09-21 01:00:02] [info]: Cloud clean done.
[2020-09-22 01:00:03] [info]: Cloud clean done.
[2020-09-23 01:00:02] [info]: Cloud clean done.
[2020-09-23 12:44:27] [info]: Creating new snapshot...
[2020-09-23 13:24:27] [error]: Can't create new snapshot (Timeout awaiting 'request' for 2400000ms)

The local snapshot got created and has the size of 691 MB.
But there is no snapshot in my nextcloud folder.

**Comment by Sebclem** [comment]
It seems to be caused by you snapshot taking more than 2400000ms (40min ?) to be created. If you create a snapshot from the supervisor interface, how many time it take to finish building the snapshot ?

**Comment by Lenny5156** [comment]
It took 44min to finish the snapshot

**Comment by Sebclem** [comment]
Ok, tomorrow I will make a quick fix ( increasing the time-out ) and when I have more time, I think I will add a setting to change the time out value.

**Comment by Sebclem** [comment]
I have made a release yesterday (0.9.1),  just tell me if this one fix your issue

**Comment by Lenny5156** [comment]
The bug is fixed.
