### ISSUE TITLE
Can't connect to Nextcloud (Error: getaddrinfo ENOTFOUND https) !

### ISSUE THREAD

**Issue by BuZZ-dEE** [Sebclem/hassio-nextcloud-backup#268]
**Describe the bug**
Can not connect to Nextcloud https://cloud.disroot.org

> Can't connect to Nextcloud (Error: getaddrinfo ENOTFOUND https) !

**To Reproduce**
Insert Nextcloud URL, username and app password and set ssl on

**System information**
- Home Assistant Version : 2024.10.2
- Home Assistant Supervisor Version : 2024.10.2
- Nextcloud Version : 29.0.4
- Addon version :  newest from your repo

**Comment by pHamala** [comment]
Maybe this will help

[https://github.com/Sebclem/hassio-nextcloud-backup/issues/15](url)
