### ISSUE TITLE
Problem with self signed certificate

### ISSUE THREAD

**Issue by christianerlinger** [Sebclem/hassio-nextcloud-backup#27]
Hello! 

I've been looking for a way ease my manual home-assistant-to-nextcloud backup - so thanks for the plugin - this would be exactly what I am looking for :).

I have a problem with the certificate I am using with my nextcloud installation.

I installed nextcloudpi (https://ownyourbits.com/nextcloudpi/) which by default would use a letsencrypt certificate; however; I don't own a public domain, and frankly I don't want to have my private nextcloud romaing around the internet. So basically I am running nextcloud with a self signed certificate (and it never ever will be available through a public domain)

When trying to connect the plugin throws an error about the self signed certificate:
```
[2020-10-09 19:38:24] [info]: Initilizing and checking webdav client...
[2020-10-09 19:38:25] [error]: Can't connect to Nextcloud (Error: self signed certificate) !
(node:248) UnhandledPromiseRejectionWarning: Can't connect to Nextcloud (Error: self signed certificate) !
(node:248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1783)
(node:248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-10-10 09:52:47] [info]: Initilizing and checking webdav client...
[2020-10-10 09:52:47] [error]: Can't connect to Nextcloud (Error: self signed certificate) !
[2020-10-10 09:56:31] [info]: Initilizing and checking webdav client...
[2020-10-10 09:56:31] [error]: Can't connect to Nextcloud (Error: Request failed with status code 400) !
```

So I disabled SSL only with nextcloudpi and retried with http instead which got me a HTTP-400 (you can see it in the log as well). I can access my nextcloud interface in the browser via http and https without an error. I checked the server logs of my nextcloud installation, but so far have not been able to get any informations about the error in there. 

Do you have any idea how to resolve this? A quick and dirty fix might be an option to disable ssl validation at all (as already mentioned this will only be available in my internal network, so this would suffice in my case even if it is dangerous in every other case), or maybe an option to manually ensure the certificate chain so I'd have a valid certificate chain again. Or of course I'd be happy to use no ssl with the backup as well - but the http 400 prevents that (of course there is no guarantee that the http 400 will turn up with ssl as well when the self signed certificate problem is gone).

thanks in advance!
best regards
Christian

**Comment by Sebclem** [comment]
Hi,

First, I can add a setting to disable strict SSL verification and we can check after that the 400 errors, can I juste have your nextcloud et home assistant version ?

**Comment by christianerlinger** [comment]
Hi!

My apologies for not providing those informations initially;

I am running Nextcloud 19.0.3.1

Home Assistant:

```
arch | armv7l
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7
python_version | 3.8.5
supervisor | 247
version | 0.116.2
```

And the latest Version of Nextcloud BackuP
Current version: 0.9.1 

cheers

**Comment by Sebclem** [comment]
I have made a release, you can update and in nextcloud settings enable "Accept Self-signed certificate".
Let me know if it fix your issue.

**Comment by christianerlinger** [comment]
Hi,
Thanks for the update. I upgraded and retried with the new setting - I still get the same error:


```
[2020-10-12 21:10:57] [error]: Nextcloud connection : FAIL !
[2020-10-12 21:10:57] [error]: ... Can't connect to Nextcloud (Error: self signed certificate) !
[2020-10-12 21:11:25] [info]: Initilizing and checking webdav client...
[2020-10-12 21:11:25] [error]: Can't connect to Nextcloud (Error: self signed certificate) !
```

Thanks & regards
Christian

**Comment by Sebclem** [comment]
I'm currently installing a nextcloud test server with self signed certificate, i will come back to you when I have a fix

**Comment by christianerlinger** [comment]
Hi,

Thanks for your efforts.

If I may - this
https://docs.nextcloudpi.com/en/how-to-get-started-with-ncp-docker/

Should be almost 100% like my setup (I installed ncp on bare metal) and should be easy to set up.

Just a tip :).

Cheers

**Comment by Sebclem** [comment]
Can you try upgrading to 0.9.3 ?

I have successfully connected to my self signed server with this fix

**Comment by christianerlinger** [comment]
Hi,
Thanks for the fix. The certificate error is gone now, unfortunately like without ssl I am running into a http 400. I'll try a new nextcloud installation and check if the error persists.

Thanks and regards!

**Comment by Sebclem** [comment]
I have found this that I think can help you : https://github.com/nextcloud/server/issues/12656

When you launch the nextcloudpi, you need to provide a domain, it's maybe because you don't use the same in the nextcloud-backup setting.

**Comment by christianerlinger** [comment]
Hi!

Thanks for the pointer - indeed the domain was missing in the config. Now It works like a charm. Thank you very much!

cheers

**Comment by Sebclem** [comment]
You're welcome, and thank your for the coffee :wink:
