### ISSUE TITLE
Manual given filenames

### ISSUE THREAD

**Issue by poudenes** [Sebclem/hassio-nextcloud-backup#29]
Hi There,

Nice work !!!!

Would be nice to have the option to give your own format for the file name.
So you can change your name like this:

HA_NC_{date}
Nextcloud_{date}_{ha_version}
Full_Backup_{ha_version}_{date}_{time}
{date}_{time}_full_backup

Etc etc etc.

**Comment by Sebclem** [comment]
Hi, 
Good idea ! 
I will take a look at this !

**Comment by Sebclem** [comment]
A have made a new release ([V0.11.0](https://github.com/Sebclem/hassio-nextcloud-backup/releases/tag/0.11.0)) If you can try this new version. 
Just let me know if you find any bug.

**Comment by poudenes** [comment]
It's not show as update in the supervisor dashboard section. Maybe have to wait untill updated
