### ISSUE TITLE
New add-on to get all the info of Nextcloud in sensor entities

### ISSUE THREAD

**Issue by poudenes** [Sebclem/hassio-nextcloud-backup#31]
Hi,

Love your Backup solution.... Your add on ignore the self signed SSL Cert.
The nextcloud  integration does not work with self signed Certs...

Maybe you can build a Add-on To collect all the info from:

https://<IP NUMBER>/ocs/v2.php/apps/serverinfo/api/v1/info

Would be great to have those information in sensors 👍

**Comment by Sebclem** [comment]
Hi,
First, Thank you for your support ! 👍 
I think it's maybe a better idea to open an new issue home-assistant/core and ask for self signed certificate support. 
My addon is not creating any sensors in home assistant at this time.

**Comment by poudenes** [comment]
Create a issue
