### ISSUE TITLE
Implement Partial Backup

### ISSUE THREAD

**Issue by klaus1k** [Sebclem/hassio-nextcloud-backup#33]
I really like the Auto-Update of this Addon. Big thanks to everybody contributing to it!

I now have a problem: since i now moved to an SSD on my Raspberry Pi, I can finally use the Plex Add-on with Movies in the \share folder. Now the full Backup has blown up to 36GB, which is obviously not feasible.

I would really love the possibility of partial Backups, so that I could exclude the \share-folder and continue using this awesome Addon.

**Comment by Sebclem** [comment]
I will take a look a this !

**Comment by Sebclem** [comment]
Can you try the new version? 
I have added folder and addon selection in the Backup setting menu.
If you have any issue, let me know.

**Comment by klaus1k** [comment]
Awesome change, thanks a lot! I tried it with manual backup and it worked. Scheduled automated Backup, will let you know if i have any issues.

**Comment by Sebclem** [comment]
i'm closing this issue, if you found any issue with this new feature, feel free to open a new one.
Thank for your support ! :smiley:
