### ISSUE TITLE
Cosmetic change

### ISSUE THREAD

**Issue by poudenes** [Sebclem/hassio-nextcloud-backup#34]
Hi ALl,

When filename is long the date of creation goes to next line. Its not nice. Maybe this can be changed?
Always creation data on next line below the filename? Or font size smaller?

![Schermafbeelding 2020-11-24 om 13 53 09](https://user-images.githubusercontent.com/4399532/100096567-7b928180-2e5c-11eb-9ff9-aadbe6b16256.png)

**Comment by Sebclem** [comment]
I'm currently using a css framework MaterializeCss that is no longer maintained.
I'm going to move all to Bootstrap and i planning to use home assistant theming.
I will fix this issue at the same time.

**Comment by Sebclem** [comment]
@poudenes It should be fix with the new web interface, can you confirm ?

**Comment by poudenes** [comment]
> @poudenes It should be fix with the new web interface, can you confirm ?

Ohh WOW ... Very nice change!! Yes fix is working, and seems even BETTER!
