### ISSUE TITLE
Incorporate into home assistant community add-ons

### ISSUE THREAD

**Issue by kicker334** [Sebclem/hassio-nextcloud-backup#35]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'm wondering if it is possible to incorporate this app into the official community add ons? It is a really good app and I feel it is fairly stable by now. 

**Describe alternatives you've considered**
Works great

**System information**
Not really applicable here... 
- Home Assistant Version :
- Home Assistant Supervisor Version :
- Nextcloud Version : 
- Addon version : 
- If any, reverse proxy in fort on Nextcloud : 

**Additional context**
NA

**Comment by Sebclem** [comment]
I have already contacted Freck on Discord, and sadly, the community add on does not accept new addons.
In community addon readme:

> ## Adding a new add-on
> We are currently not accepting third party add-ons to this repository.

**Comment by kicker334** [comment]
Shame! Thanks for letting me know.
