### ISSUE TITLE
Hourly Backups

### ISSUE THREAD

**Issue by meichthys** [Sebclem/hassio-nextcloud-backup#36]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a feature request for an awesome add-on

**Describe the solution you'd like**
It would be nice to be able to take automated Hourly backups or backups more than once a day.

**Describe alternatives you've considered**
I find myself wishing i had more backups durring the day. I sometimes make large changes to Homeassitant and then wish there was a way to restore back to a point a few hours earlier. I currently use Proxmox to take snapshots of my Home-Assistant VM, so that's another option, but it would be an appreciated feature to allow Hourly backups to be stored in Nextcloud, however i could see that this could become i/o intensive and may not be reasonable.

**System information**
- Home Assistant Version : 0.118
- Home Assistant Supervisor Version : 2020.12.6
- Nextcloud Version : 20
- Addon version : 
- If any, reverse proxy in fort on Nextcloud :  NGINX

**Additional context**
![image](https://user-images.githubusercontent.com/10717998/102099830-baca4780-3df6-11eb-8062-b92a24e59deb.png)

**Comment by Sebclem** [comment]
Hi,
Sorry for late reply, i don't think hourly backup is a good idea, like you said, il will cause high i/o and CPU load.
Actually on my HA, it take ~10min to build a snapshot.
But you can maybe use the `manual backup` button as alternative to Snapshots.

**Comment by meichthys** [comment]
Sounds reasonable to me. Great add on! Nextcloud is great! I've created the nextcloud integration for getting general nextcloud information into homeassistant: https://www.home-assistant.io/integrations/nextcloud/
