### ISSUE TITLE
Encrypted backups

### ISSUE THREAD

**Issue by PaulAntonDeen** [Sebclem/hassio-nextcloud-backup#42]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
In local backups you can use password encryption so that backups can only be extracted by the rightfull owner. I would like to be able to encrypt before upload to nextcloud.

**Describe alternatives you've considered**
No alternatives

**System information**
- Home Assistant Version : 2021.1.1
- Home Assistant Supervisor Version : 2020.12.7
- Nextcloud Version : 
- Addon version : 0.13.1
- If any, reverse proxy in fort on Nextcloud : NGINX

**Additional context**
Thanks for the addon, it looks and works great!

**Comment by Sebclem** [comment]
Hi,
I will take a look a this and i think it will be not difficult to implement this.

The only stuff you need to know, is that the encryption password will be stored in the addon configuration. This config can't be accessible outside of the addon, so i think is not an issue.

**Comment by ronaldt80** [comment]
Would be a nice addition. The Home Assistant Google drive backup addon has this functionality.

[https://github.com/sabeechen/hassio-google-drive-backup](https://github.com/sabeechen/hassio-google-drive-backup)

**Comment by Sebclem** [comment]
Added by the last release, let me know if you find any issue :+1:

**Comment by ronaldt80** [comment]
Will test over the weekend and let you know
