### ISSUE TITLE
Stop selected addons before back up

### ISSUE THREAD

**Issue by poudenes** [Sebclem/hassio-nextcloud-backup#45]
I All,

Would be nice to have a option where you can select addons that can be stopped before they get backup.
Some use dB and the dB can be corrupt when you want restore them.

When you stop them, and start them when the backup is done you will prevent a possible corrupt dB in your backups.

Cheers

**Comment by Sebclem** [comment]
I will take a look a this this weekend :+1:

**Comment by Sebclem** [comment]
Added in 0.15, I close this issue, open a new one if you found any bug

**Comment by poudenes** [comment]
smaal question. After backup the addon will start the addons automatic :) just to be sure

**Comment by Sebclem** [comment]
Yes of course
