### ISSUE TITLE
Snapshots always listed as partial !

### ISSUE THREAD

**Issue by vincegre** [Sebclem/hassio-nextcloud-backup#63]
I have setup the plugin to do a full backup each night and upload it at my NC. So far it looks to work but when I go in Supervisor to see list of snapshots locally done, I can see the automated ones done by the plugin but they are listed as partial snapshot (although if I look at details of them they look to be a full snapshot !)

Steps to reproduce the behavior: Setup a full backup each night

Expected behavior: should be full snapshot and not partial ones !

- Home Assistant Version : 2021.4.5
- Home Assistant Supervisor Version : supervisor-2021.04.1
- Nextcloud Version : 21.0.1
- Addon version : 0.16.0
- If any, reverse proxy in fort on Nextcloud : N/A

**Comment by Sebclem** [comment]
A partial snapshot with everything selected is exactly the same as a full snapshot.

The only things that differ is the API endpoint used : 
`/snapshots/new/full` for full
`/snapshots/new/partial` for partial

I can add a check, if everything is selected, use `/snapshots/new/full` instead of `/snapshots/new/partial`, but this is only a aesthetic/naming issue, as the 2 type generated file are the same if we exclude none of the folders/addons

**Comment by vincegre** [comment]
> A partial snapshot with everything selected is exactly the same as a full snapshot.

Fully agree on that but it's making it pretty confusing to know which backups are full or partial as they all appear as partial ;)

> I can add a check, if everything is selected, use `/snapshots/new/full` instead of `/snapshots/new/partial`, but this is only a aesthetic/naming issue, as the 2 type generated file are the same if we exclude none of the folders/addons

Hum I would have an other suggestion that would avoid also a drawback of your plugin. Instead of having to select everything, make it either full snapshot and then use the full api endpoint or manual as it is now where you tick/untick what you want and then select partial api endpoint ! It would avoid a big issue of your plugin right now: if I add a new plugin in hassio and don't go back in the backup plugin to tick that new plugin it'll be never backuped...

**Side note: it's really a great plugin you made there** and love it ;) If I can help for translation or whatever would be happy too ;)

**Comment by tomershvueli** [comment]
I'm seeing this issue as well. Would be to have full backups actually show up as 'full'. The 'partial' gave me half a heart attack before I started reading into it...

**Comment by vincegre** [comment]
Any chance to get it fixed at a time ?

**Comment by Sebclem** [comment]
I'm working on a major rewrite that will fix this issue, you can see what's planed in #192

**Comment by vincegre** [comment]
> I'm working on a major rewrite that will fix this issue, you can see what's planed in #192

Thanks for the update and that's really nice :) impatient to be able to test the completely rewritten version of the add-on ;) Good luck !
