### ISSUE TITLE
Fail to upload snapshot to nextcloud (Error: write ECONNRESET) !

### ISSUE THREAD

**Issue by scrafiiii** [Sebclem/hassio-nextcloud-backup#71]
**Describe the bug**
Addon won't upload snapshots created to my Nextcloud

**To Reproduce**
Start a manual Backup, the snapshot will be created but the Addon can't add upload the snapshot and fails with the error message: "Fail to upload snapshot to nextcloud (Error: write ECONNRESET) !"

**Expected behavior**
Upload Snapshot to Folder in Nextcloud

**System information**
- Home Assistant Version : core-2021.6.5
- Home Assistant Supervisor Version : supervisor-2021.06.3
- Nextcloud Version :  Nextcloud 21.0.2
- Addon version : 0.16.1
- If any, reverse proxy in fort on Nextcloud : traefik2

**Additional context**
- I can write in the folder I try to upload the snapshots into
- So far my Nextcloud works flawlessly (webdav, reverse proxy config, Client)
- tried App Password and User password, both didn't work
- the Addon can write into the folder (I can see that it created the folders manual, auto etc.)
- somehow the addin was able to do one successfull upload

**Logs**

> [2021-06-19 15:24:36] [error]: 	Fail to upload snapshot to nextcloud (Error: write ECONNRESET) !
> [2021-06-19 15:24:36] [error]: 	Error: write ECONNRESET
>     at afterWriteDispatched (internal/stream_base_commons.js:156:25)
>     at writeGeneric (internal/stream_base_commons.js:147:3)
>     at Socket._writeGeneric (net.js:785:11)
>     at Socket._write (net.js:797:8)
>     at doWrite (internal/streams/writable.js:377:12)
>     at clearBuffer (internal/streams/writable.js:529:7)
>     at Socket.Writable.uncork (internal/streams/writable.js:317:7)
>     at connectionCorkNT (_http_outgoing.js:733:8)
>     at processTicksAndRejections (internal/process/task_queues.js:79:21)
> (node:396) UnhandledPromiseRejectionWarning: Fail to upload snapshot to nextcloud (Error: write ECONNRESET) !
> (node:396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

Any help would be appreciated, thanks!

**Comment by SNThrailkill** [comment]
@nicoscrafi did you ever get this fixed?

**Comment by nicoscrafi** [comment]
No, sadly not really, sometimes it worked, but mostly it didn't. I currently don't use this Plugin (and Nextcloud) anymore, so I didn't dig deeper myself.

**Comment by SNThrailkill** [comment]
Darn, yeah im gonna have to give this up too. its been a couple of weeks and my backups are stale at this point. Thanks for your answer.
