### ISSUE TITLE
Fail to upload snapshot to nextcloud (HTTPError: Response code 413 (Request Entity Too Large)) !

### ISSUE THREAD

**Issue by patrice-guillemette** [Sebclem/hassio-nextcloud-backup#75]
Whenever I try to upload a backup, I get this error. It was working prior to last update.

**Comment by Sebclem** [comment]
Hi,
I don't think this is related to the update, 
I think your backup size have reached more than 100MB (due to your homeassistant.db and other stuff growing) so this is related to  => #9 (pined issue)

**Comment by frehall** [comment]
Im running nextcloud behind a Nginx Proxy Manager and havent been able to solve this problem.

Ive added/changed `client_max_body_size 0;` in /config/nginx/nginx.conf as well ass `upload_max_filesize` in /etc/php*/php.ini 

As of what I can find these are the settings that has solved the problem for most people but for me no success.
