### ISSUE TITLE
Make backup planning more granular

### ISSUE THREAD

**Issue by Liwindo** [Sebclem/hassio-nextcloud-backup#78]
Hi,
first of all thx for this Add-on. It is really helpfull.

My request:
For now it is only possible to plan a backup on a daily, weekly or monthly basis. Is it possible to make this more granular, that you can e.g. trigger a backup every 3 days?

I am not aware about of the limitations of the home assistent API but as per cron default it is possible to set e.g. "0 0 */3 * *"  for 00:00 (midnight) every three days.

**Comment by Sebclem** [comment]
I will take a look a this, i can add a mode where you can define a custom cron setting.
I will add this when i'm back from holiday

**Comment by Sebclem** [comment]
Added with the last version :+1:
