### ISSUE TITLE
Can't connect to Nextcloud (Error: getaddrinfo EAI_AGAIN https) !

### ISSUE THREAD

**Issue by joeyboon** [Sebclem/hassio-nextcloud-backup#79]
Hi there,

Was hoping to try your plugin! Sounds like exactly the thing I was looking for. However I can't get it to work. Does your plugin use different DNS servers then the system? I keep getting the "Can't connect to Nextcloud (Error: getaddrinfo EAI_AGAIN https) !" while my browser is perfectly able to resolve my Nextcloud instance and I was able to add your repo (so DNS works on HomeAssistant). I block other DNS traffic on my network since I use blocklists etc. So if your plugin uses different servers that's the problem. Any way to set them manually if that's the case? Thanks for developing this plugin! Could be a lifesaver when it works!

**Comment by Sebclem** [comment]
Hi,
The plugin don't override any DNS settings, but I think you are filling the hostname field badly:
You only need to put the hostname in this field, example: if you use `https://mynexcloud.net` to access to your nextcloud, you need to put only `nextcloud.net` in the hostname field.

**Comment by joeyboon** [comment]
@Sebclem How stupid if me. It even said so in the example! Thanks for the fast reply!
