### ISSUE TITLE
Fail to upload snapshot to nextcloud (Status code: 413) !

### ISSUE THREAD

**Issue by rrosson** [Sebclem/hassio-nextcloud-backup#9]
Running manually.  The log is below
```
[2020-02-19 13:35:55] [info]: Local clean done.
[2020-02-19 13:44:15] [info]: Stoping Cron...
[2020-02-19 13:44:15] [info]: Starting Cron...
[2020-02-19 13:44:38] [info]: Creating new snapshot...
[2020-02-19 13:45:23] [info]: Snapshot created with id 2186a8b6
[2020-02-19 13:45:23] [info]: Downloading snapshot 2186a8b6...
[2020-02-19 13:45:23] [info]: Download success !
[2020-02-19 13:45:23] [info]: Uploading snap...
[2020-02-19 13:45:25] [error]: Fail to upload snapshot to nextcloud (Status code: 413) !
(node:354) UnhandledPromiseRejectionWarning: Fail to upload snapshot to nextcloud (Status code: 413) !
(node:354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by Sebclem** [comment]
Hi !
Can i have the size of your backup file? Because in webdav, `413` is `Request Entity Too Large`.

**Comment by rrosson** [comment]
The backup is  242257920 (232M). Please let me know if there is anything further I can provide.

**Comment by Sebclem** [comment]
I'm not sure but i think it's more an issue with your setup, not with the addon. 
Do you have a proxy in front of Nextcloud ?

**Comment by rrosson** [comment]
nextcloud is installed from snap on an 18.0X server.

**Comment by Sebclem** [comment]
Do you have Nginx in front of nextcloud (or other reverse proxy)? I found a similar issue on the Nexcloud-snap repo  (https://github.com/nextcloud/nextcloud-snap/issues/1017)

**Comment by rrosson** [comment]
client_max_body_size was the culprit.

**Comment by aluavin** [comment]
Leaving this for future people:
If you're running Nextcloud on unRaid with Let's Encrypt Docker. Have a look in the appdata/letsencrypt/nginx/proxy.conf

Took me some time to check for all .conf files.

**Comment by c0rnflake** [comment]
I'm running Nextcloud & SWAG dockers unraid and running into the same issue.  Could someone share a working NC/SWAG config?

**Comment by ubl8** [comment]
Hey, I know this is already closed but this might help some others to save time in searching for a result.

I hat the same problem with 413 Error and nothing here or on the web I found helped me.
To make it short I found the fix.

I have Nextcloud installed on Unraid with a reverse proxy swag (letsencrypt).
After searching through all proxy.conf - ngingx.conf - nextcloud.subdomain.conf - ...conf files for a fix and nothing changed,
following fixed it for me.

1. Search in the nextcloud container shell for /etc/php*/php.ini and change the upload_max_filesize and post_max_size to something bigger (ex. 10G).
2. Search in the nextcloud container shell for /config/nginx/site-confs/default and change the client_max_body_size to 0 (mine was set to 512).
3. Eventually also check the /config/nginx/nginx.conf and appdata/swag/nginx/proxy-conf/nextcloud.subdomain.conf if client_max_body_size is set to 0;

At least this helped me to get the NC Backup to upload my snapshots succesfully.

**Comment by frehall** [comment]
Im running nextcloud behind a Nginx Proxy Manager and havent been able to solve this problem.

Ive added/changed `client_max_body_size 0;` in /config/nginx/nginx.conf as well ass `upload_max_filesize` in /etc/php*/php.ini 

As of what I can find these are the settings that has solved the problem for most people but for me no success.

**Comment by ubl8** [comment]
> Im running nextcloud behind a Nginx Proxy Manager and havent been able to solve this problem.
> 
> Ive added/changed `client_max_body_size 0;` in /config/nginx/nginx.conf as well ass `upload_max_filesize` in /etc/php*/php.ini 
> 
> As of what I can find these are the settings that has solved the problem for most people but for me no success.

I recently noticed that I could not upload big files (> 100MB) to nextcloud because I use Cloudflare as extra layer of security as a Proxy and because I dont have an Enterprise subscription the upload size is limited to 100MB.

If you checked/changed all config files but the problem still exists, maybe this is an similar issue as mine above.

**Comment by frehall** [comment]
> > Im running nextcloud behind a Nginx Proxy Manager and havent been able to solve this problem.
> > Ive added/changed `client_max_body_size 0;` in /config/nginx/nginx.conf as well ass `upload_max_filesize` in /etc/php*/php.ini
> > As of what I can find these are the settings that has solved the problem for most people but for me no success.
> 
> I recently noticed that I could not upload big files (> 100MB) to nextcloud because I use Cloudflare as extra layer of security and because I dont have an Enterprise subscription the upload size is limited to 100MB.
> 
> If you checked/changed all config files but the problem still exists, maybe this is an similar issue as mine above.
> 
> For me I could fix this issue by using the direct IP (same Network) of the Nextcloud server and not use a domain name.

Changed NextCloud to local IP and can confirm it worked. Thanks alot ubl8!

**Comment by vdwals** [comment]
Hi, I experience the same issue and none of the above solutions could yet fix it.

I can download the backups from Home Assistant and upload them via the Web UI, the same endpoint effectively the addon would use. But the addon return 413. I could not find a related entry in the nextcloud logs.

Nextcloud is running behind the Nginx Proxy Manager, but neither the external accessible URL nor the local IP address work.

Also the nextcloud system information shows the correct limits (16 gb in my instance), but only the addon is not able to upload 1.6 or 1.8 gb files.

**Comment by ubl8** [comment]
> Hi, I experience the same issue and none of the above solutions could yet fix it.
> 
> I can download the backups from Home Assistant and upload them via the Web UI, the same endpoint effectively the addon would use. But the addon return 413. I could not find a related entry in the nextcloud logs.
> 
> Nextcloud is running behind the Nginx Proxy Manager, but neither the external accessible URL nor the local IP address work.
> 
> Also the nextcloud system information shows the correct limits (16 gb in my instance), but only the addon is not able to upload 1.6 or 1.8 gb files.

If you say non of the above solutions work, I gues you checked all of the .conf files? There might be more than one file affecting this...

Also uploading via the Web UI is not the same as with the Container... The Web UI uploads in more small peaces to prevent this issues...

**Comment by Sebclem** [comment]
> > Hi, I experience the same issue and none of the above solutions could yet fix it.
> > 
> > I can download the backups from Home Assistant and upload them via the Web UI, the same endpoint effectively the addon would use. But the addon return 413. I could not find a related entry in the nextcloud logs.
> > 
> > Nextcloud is running behind the Nginx Proxy Manager, but neither the external accessible URL nor the local IP address work.
> > 
> > Also the nextcloud system information shows the correct limits (16 gb in my instance), but only the addon is not able to upload 1.6 or 1.8 gb files.
> 
> If you say non of the above solutions work, I gues you checked all of the .conf files? There might be more than one file affecting this...
> 
> Also uploading via the Web UI is not the same as with the Container... The Web UI uploads in more small peaces to prevent this issues...

I'm currently working on a new version that will include chunked upload to prevent the 413 error, at this time I can't give ETA because this new version will also include a migration to vuejs that requires a lot of work.

You can follow my progress on the `vue` branch

**Comment by jclsn** [comment]
Unfortunately none of the solutions here could solve my issue either

**Comment by jclsn** [comment]
If anyone else is using the Nextcloud Docker image. Here is what I did to solve it

https://help.nextcloud.com/t/cant-upload-files-over-512mb-using-ha-nc-backup-to-nc-docker-image-nginx-proxy-manager/171392/3
