### ISSUE TITLE
Error State and Code?

### ISSUE THREAD

**Issue by SkylightXD** [Sebclem/hassio-nextcloud-backup#91]
Hi :)

could you add some informations about the error state and code?
I like to trigger a message, if there is any probleme in the backup process.

I found this error code in the data:
Error Codes
    1 => Fail to download snap
    2 => Nextcloud config invalid
    3 => Can't connect to Nextcloud
    4 => Upload snap fail
    5 => Fail create new snap
    6 => Fail to clean
    7 => Fail to download snap
    8 => Fail to stop addon
    9 => Fail to start addon
 Are they right?

Thanks and regards

**Comment by SkylightXD** [comment]
Great! And the error state switch to on if there is any error?

**Comment by Sebclem** [comment]
Yes
